tienda_vinilos/tienda_app/urls.py
from django.urls import path
from .views import home,editar
from .views import home,registro
from .views import home,login2
from .views import home,agregar_producto,listar_productos,eliminar_producto,catalogo, procesar_orden, perfil_producto
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

#URLS donde se registran los templates a usar

urlpatterns = [

    path('', home, name="home"),
    path('contacto/',contacto, name= "contacto"),
    path('editar/<id>',editar, name= "editar"),
    path('login2/',login2, name= "login2"),
    path('registro/',registro, name= "registro"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('agregar-genero/', agregar_genero, name="agregar_genero"),
    path('agregar-artista/', agregar_artista, name="agregar_artista"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lista-productos/',listar_productos, name= "lista_productos"),
    path('eliminar-producto/<id>', eliminar_producto, name = "eliminar_producto"),
    path('catalogo/',catalogo, name= "catalogo"),
    path('editar-productos/<id>', editar_producto, name = "editar_producto"),
    path('update_item/',updateItem, name= "update_item"),
    path('carrito/',carrito, name= "carrito"),
    path('compra/',compra, name= "compra"),
    path('producto-perfil/<id>',perfil_producto, name= "perfil_producto"),
    path ('procesar_orden/',procesar_orden, name="procesar_orden"),
 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda_vinilos/tienda_vinilos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda_app.urls'))


]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda_vinilos/tienda_app/models.py
#Archivo para la creacion de tablas en la Base de Datos

from django.db import models
from django.contrib.auth.models import User

#Tabla de Usuarios

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    celular = models.CharField(max_length=30)
    direccion = models.CharField(max_length=100)
    edad = models.CharField(max_length=100)
    pais=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

#Tabla de Artistas

class Artista(models.Model):
    nombre = models.CharField(max_length=70)
    imagen = models.ImageField(upload_to="artistas", null=True, blank=True)
    def __str__(self):
        return self.nombre

#Tabla de Generos

class Genero(models.Model):
    nombre = models.CharField(max_length=70)

    def __str__(self):
        return self.nombre

#Tabla de productos

class Producto(models.Model):
    nombre = models.CharField(max_length=70)
    genero = models.ForeignKey(Genero, on_delete=models.PROTECT)
    artista = models.ForeignKey(Artista, on_delete=models.PROTECT)
    descripcion= models.TextField(max_length=700)
    stock = models.IntegerField()
    precio = models.IntegerField()
    
    imagen = models.ImageField(upload_to="productos", null=True)
    
    
    def __str__(self):
        return self.nombre

#Tabla de Ordenes del carrito

class Orden(models.Model):
    user= models.ForeignKey(PerfilUsuario, on_delete=models.SET_NULL, blank=True, null=True)
    fecha_orden=models.DateTimeField(auto_now_add=True)
    completo= models.BooleanField(default=False, null=True, blank=True)
    transaccion_id=models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping=False
        ordenproductos = self.ordenproducto_set.all()
        for i in ordenproductos:
            shipping= True
        return shipping

    @property
    def get_cart_total(self):
        ordenproductos = self.ordenproducto_set.all()
        total=sum([producto.get_total for producto in ordenproductos])
        return total
    
    @property
    def get_cart_items(self):
        ordenproductos = self.ordenproducto_set.all()
        total=sum([producto.cantidad for producto in ordenproductos])
        return total
        
#Tabla de procesamiento de Ordenes

class OrdenProducto(models.Model):
    producto= models.ForeignKey(Producto,on_delete=models.SET_NULL, blank=True, null=True)
    orden = models.ForeignKey(Orden, on_delete=models.SET_NULL, blank=True, null=True)
    cantidad= models.IntegerField(default=0, null=True, blank=True)
    fecha_agregada = models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
        total=self.producto.precio * self.cantidad
        return total

#Tabla de delivery 

class Shipping(models.Model):
    user= models.ForeignKey(PerfilUsuario, on_delete=models.SET_NULL, blank=True, null=True)
    orden=models.ForeignKey(Orden, on_delete=models.SET_NULL, blank=True, null=True)
    direccion = models.CharField(max_length=200, null=True)
    ciudad= models.CharField(max_length=200, null=True)
    estado= models.CharField(max_length=200, null=True)
    codigo_postal = models.CharField(max_length=200, null=True)
    fecha_agregada= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.direccion

tienda_vinilos/tienda_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import * 
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm,Perfilform,Modform,Productoform
from django.contrib.auth import authenticate,login
from .filters import ProductFilter
from .forms import *
from django.core.paginator import Paginator, EmptyPage
from django.http import Http404
from django.http import JsonResponse
import json
import datetime

#Funciones a usar en los templates

#Funciones del home de la pagina

def home(request):
    productos = Producto.objects.all()
    data = {
        'productos': productos
    }
    return render(request, 'tienda_app/home.html', data)

#Funciones de la seccion contacto de la pagina

def contacto(request):

    return render (request, 'tienda_app/contacto.html')

#Funciones del login por defecto de Django

def login1(request):

    return render (request, 'registration/login.html')

#Funciones del Catalogo de productos de la pagina

def catalogo(request):
    context = {}
    #productos = Producto.objects.all()
    myFilter = ProductFilter(
        
        request.GET,
        queryset=Producto.objects.all()
        
    )
    context['myFilter'] = myFilter

    productos_filtrados_paginados  = Paginator(myFilter.qs,6)

    page_numb = request.GET.get('page',1)
    
    person_page_obj = productos_filtrados_paginados.get_page(page_numb)
    context['person_page_obj'] = person_page_obj


    return render(request, 'tienda_app/catalogo.html', context=context)

#Funciones del carrito

def carrito(request):
    if request.user.is_authenticated:
        user = request.user.perfilusuario
        orden, created = Orden.objects.get_or_create(user=user,completo=False)
        productos = orden.ordenproducto_set.all()
    else:
        productos =[]
        orden = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
    context={'productos': productos, 'orden': orden}
    return render(request, "Producto/carrito.html", context)


def compra(request):
    if request.user.is_authenticated:
        user = request.user.perfilusuario
        orden, created = Orden.objects.get_or_create(user=user,completo=False)
        productos = orden.ordenproducto_set.all()
    else:
        productos =[]
        orden = {'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
    context={'productos': productos, 'orden': orden}
    return render(request, "Producto/compra.html", context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action=data['action']

    print('Action:', action)
    print ('productId:', productId)

    user = request.user.perfilusuario
    producto = Producto.objects.get(id=productId)
    orden, created = Orden.objects.get_or_create(user=user,completo=False)

    ordenProducto, created = OrdenProducto.objects.get_or_create(orden=orden, producto=producto)

    if action == 'add':
        ordenProducto.cantidad= (ordenProducto.cantidad+1)
    elif action == 'remove':
        ordenProducto.cantidad = (ordenProducto.cantidad-1)
        

    ordenProducto.save()

    if action == 'delete':
        messages.error(request,"Producto Eliminado")
        ordenProducto.delete()

    if ordenProducto.cantidad <= 0:
        messages.error(request,"Producto Eliminado")
        ordenProducto.delete()
    
    return JsonResponse ('Producto fue agregado', safe=False)

#Funciones del procesamiento de ordenes

def procesar_orden(request):

    transaccion_id=datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:

        user = request.user.perfilusuario
        orden, created = Orden.objects.get_or_create(user=user, completo=False)
        total = float(data['form']['total'])
        orden.transaccion_id = transaccion_id

        if total == orden.get_cart_total:
            orden.completo = True
        orden.save()

        if orden.shipping == True:
            Shipping.objects.create(
                user=user,
                orden=orden,
                direccion=data['shipping']['address'],
                ciudad=data['shipping']['city'],
                estado=data['shipping']['state'],
                codigo_postal=data['shipping']['zipcode'],
            )

    else:
        print('Usuario no registrado')
        
    return JsonResponse('Subiendo Pago', safe=False)


#Funcion de Agregar genero

def agregar_genero(request):
    
    data={
        'form': Generoform()
    }

    if request.method == 'POST':
        formulario= Generoform(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Genero Agregado")
        else:
            data["form"] = formulario

    return render (request, 'Producto/agregar_genero.html', data)

#Funcion de agregar artista

def agregar_artista(request):
    
    data={
        'form': Artistaform()
    }

    if request.method == 'POST':
        formulario= Artistaform(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Artista Agregado")
        else:
            data["form"] = formulario

    return render (request, 'Producto/agregar_artista.html', data)

#Funcion de agregar producto

def agregar_producto(request):
    
    data={
        'form': Productoform()
    }

    if request.method == 'POST':
        formulario= Productoform(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto Agregado")
        else:
            data["form"] = formulario

    return render (request, 'Producto/agregar_producto.html', data)

#Funcion para el buscar/ filtrar productos

def listar_productos(request):
    context = {}
    #productos = Producto.objects.all()
    myFilter = ProductFilter(
        
        request.GET,
        queryset=Producto.objects.all()
        
    )
    context['myFilter'] = myFilter

    productos_filtrados_paginados  = Paginator(myFilter.qs,6)

    page_numb = request.GET.get('page',1)
    
    person_page_obj = productos_filtrados_paginados.get_page(page_numb)
    context['person_page_obj'] = person_page_obj


    return render(request, 'Producto/lista_productos.html', context=context)

#Funcion para eliminar productos

def eliminar_producto(request,id):

    producto = get_object_or_404(Producto, id = id)
    producto.delete()
    messages.success(request, "Producto Eliminado")
    return redirect(to = "lista_productos")

#Funcion para editar producto

def editar_producto(request, id):
    producto= Producto.objects.get(id=id)

    data = {

        'form' : Productoform(instance=producto)
    }

    if request.method == 'POST':
        formulario=Productoform(data=request.POST, instance=producto, files = request.FILES)

        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente", redirect(to='lista_productos'))
            data['form'] = Productoform(instance = Producto.objects.get(id=id))
            
    return render(request,'Producto/editar_producto.html' , data)

#Funciones para la edicion de un producto

def perfil_producto(request, id):
    producto= Producto.objects.get(id=id)
 
    context = {

        'id' : producto.id,
        'nombre':producto.nombre,
        'genero' : producto.genero,
        'artista': producto.artista,
        'descripcion': producto.descripcion,
        'stock':producto.stock,
        'precio' : producto.precio,
        'imagen_artista': producto.artista.imagen,
        'imagen' : producto.imagen,
    }
            
    return render(request,'tienda_app/perfil_producto.html' , context)

#Funcion para la edicion de perfil de usuario

def editar(request,id):
    user= PerfilUsuario.objects.get(id=id)
    data={
        'form': Modform(instance=user)
    }
    
    if request.method == 'POST':
        formulario=Modform(data=request.POST, instance=user)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente")
            redirect(to='home')
    else:
        formulario=Modform(instance=user)
    data['form']=formulario 
    return render (request, 'tienda_app/editar.html', data)


#Funcion del login usado por nosotros

def login2(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user= authenticate(request, username=username, password=password)      
        if user is not None:
            login(request, user)
            messages.success(request, "Ingreso Correcto")
            return redirect(to="catalogo")
        else:
            messages.error(request, "Contraseña o usario incorrecto")
    context={}
    return render (request, 'tienda_app/login2.html', context)

#Funcion del registro de usuario

def registro(request):
    if request.method == 'POST':  
        form = UserRegisterForm(request.POST)
        perfil_form=Perfilform(request.POST)
        if form.is_valid() and perfil_form.is_valid():
            user=form.save()
            perfil=perfil_form.save(commit=False)
            perfil.user=user
            perfil.save()
            username= form.cleaned_data['username']
            password= form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)      
            messages.success(request, "Registro Correcto")
            return redirect(to="catalogo")

    else:
        form=UserRegisterForm()
        perfil_form=Perfilform()   

    data={'form':form, 'perfil_form':perfil_form}
    return render (request, 'tienda_app/registro.html', data)

tienda_vinilos/tienda_app/templates/tienda_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">   
    <script src="{% static 'node_modules/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <script type="text/JavaScript">

        var user='{{request.user}}'

        function getToken(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
        const csrftoken = getToken('csrftoken');  

    </script>

    <title>
        {% block title %} {% endblock %} 
    </title>
  </head>
  <style>
    body{
        background: url('https://www.mondosonoro.com/wp-content/uploads/2019/07/discos.jpg') no-repeat;
        margin:0px;
        padding: 0px;   
        width:100%;
        height:100%;
        background-size: cover;
    }
    i {
      margin-right: 3px;
      
    }
</style>
  
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
      <div class = "container">
        <a class="navbar-brand" href="/">Vinyle Store</a>
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            
              {%if user.is_authenticated %}
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" type="button" data-toggle="dropdown">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{%url 'editar' user.perfilusuario.id %}"><span class="fas fa-edit"></span> Editar Perfil</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'logout' %}">Cerrar sesion</a></li>
                </ul>
              </li>
              
              {% else %}
              <li class = "nav-item">
                  <a class = "nav-link" href="{%url 'login2' %}"><span class="fas fa-sign-in-alt"></span> Inicia sesion </a>
              </li>


              <li class = "nav-item">
                <a class = "nav-link" href="{%url 'registro' %}">Registrarse</a>
              </li>
              {% endif %}
              <li class="nav-item active">
                <a class="nav-link" href="/"> <span class="fas fa-home"></span> Home  <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'contacto' %}"><span class="fas fa-user-tie"></span> Contacto</a>

              <li class="nav-item">
                <a class="nav-link" href="{%url 'catalogo' %}"><span class="fas fa-record-vinyl"></span> Catalogo</a>  
              {%if perms.app.add_producto %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" type="button" data-toggle="dropdown">
                  Productos
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{%url 'agregar_producto' %}"><span class="fas fa-plus"></span> Agregar</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{%url 'lista_productos' %}"><span class="fas fa-list"></span> Lista productos </a></li>
                  <li><hr class="dropdown-divider"></li>
                
                </ul>
              </li>

              {% endif %}

              {%if user.is_authenticated %}  
              <li class="nav-item">
                  <a class="nav-link disabled" href="#">       Hola {{user.first_name}}, Bienvenido</a>
              </li>
              <a style="color:#fff; margin-top: 10px;margin-left: 100px" href="{%url 'carrito' %}" class="nav-item">
                <span class="fa fa-shopping-cart fa-lg" aria-hidden="true"></span></a>
              {% endif %}
              
          </ul>
          

          


         
        </div>
      </div>
      </nav>

    {% block content %}



    {% endblock %}
    
    <style>
      /***** Footer *****/


.footer-top { padding: 60px 0; background: #333; text-align: left; color: #aaa; }
.footer-top h3 { padding-bottom: 10px; color: #fff; }

.footer-about img.logo-footer { max-width: 74px; margin-top: 0; margin-bottom: 18px; }
.footer-about p a { color: #aaa; border-bottom: 1px dashed #666; }
.footer-about p a:hover, .footer-about p a:focus { color: #fff; border-color: #aaa; }

.footer-contact p { word-wrap: break-word; }
.footer-contact i { padding-right: 10px; font-size: 18px; color: #666; }
.footer-contact p a { color: #aaa; border-bottom: 1px dashed #666; }
.footer-contact p a:hover, .footer-contact p a:focus { color: #fff; border-color: #aaa; }

.footer-social a { display: inline-block; margin-right: 20px; margin-bottom: 8px; color: #777; border: 0; }
.footer-social a:hover, .footer-social a:focus { color: #aaa; border: 0; }
.footer-social i { font-size: 24px; vertical-align: middle; }

.footer-bottom { padding: 15px 0; background: #444; text-align: left; color: #aaa; }

.footer-copyright p { margin: 0; padding: 0.5rem 0; }
.footer-copyright a { color: #fff; border: 0; }
.footer-copyright a:hover, .footer-copyright a:focus { color: #aaa; border: 0; }

/* footer navbar */
.navbar { padding: 0; background: #444; backface-visibility: hidden; }

.navbar-dark .navbar-nav { font-size: 15px; color: #fff; font-weight: 400; }
.navbar-dark .navbar-nav .nav-link { color: #fff; border: 0; }
.navbar-dark .navbar-nav .nav-link:hover { color: #aaa; }
.navbar-dark .navbar-nav .nav-link:focus { color: #aaa; outline: 0; }

.navbar-expand-md .navbar-nav .nav-link { padding-left: 1rem; padding-right: 1rem; }
    </style>
    <br><br><br><br>
    <footer >
      <div class="footer-top">
        <div class="container">
          <div class="row"> 
            <div class="col-md-4 col-lg-4 footer-contact wow fadeInDown">
              <h3>Vinyle Store</h3>
              <p>
                Somos una empresa comprometida con la venta de discos de vinilo de alta calidad.
              </p>
              <p>Gracias por elegirnos.</p>
                  </div>
            <div class="col-md-4 col-lg-4 offset-lg-1 footer-contact wow fadeInDown">
              <h3>Contactanos</h3>
                  <p><span class="fas fa-map-marker-alt"></span> Cercado de Lima 15081</p>
                  <p><span class="fas fa-phone"></span> Telefono: 01-7930289</p>
                  <p><span class="fas fa-envelope"></span> Email: vinilo.peru@gmail.com</p>
                  <p><span class="fab fa-whatsapp"></span> Whatsapp: 929426588</p>
                  </div>
                  <div class="col-md-4 col-lg-3 footer-social wow fadeInUp">
                    <h3>Siguenos</h3>
                    <p>
                      <a href="#"><span class="fab fa-facebook"></span></a> 
            <a href="#"><span class="fab fa-twitter"></span></a> 
            <a href="#"><span class="fab fa-google-plus-g"></span></a> 
            <a href="#"><span class="fab fa-instagram"></span></a> 
            <a href="#"><span class="fab fa-pinterest"></span></a>
                    </p>
                  </div>
            </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="container">
          <div class="row justify-content-center">
               <div class="col-md-5 footer-copyright">
                    <p>&copy; copyright Vinyle.com Desarrollado por <strong>Vinyle.SAC</strong></a></p>
                  </div>
             </div>
        </div>
      </div>
    </footer>
    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->


    {%if user.is_authenticated %}  
      {% if messages %}
        {% for n in messages %}
          <script>
              Swal.fire({
                title: "{{n}}",
                icon: "success" 
              })      
          </script>
        {% endfor %}
      {% endif %}
    
    {% else %}
    {% if messages %}
    {% for n in messages %}
      <script>
          Swal.fire({
            title: "{{n}}",
            icon: "error" 
          })      
      </script>
    {% endfor %}
  {% endif %}
  {% endif %}
  


  


  <script type= "text/JavaScript" src="{% static 'js/cart.js' %}"> </script>

  </body>
</html>

tienda_vinilos/tienda_app/templates/tienda_app/editar.html
{% extends "tienda_app/base.html" %}
{% load static %}

{% block title %} Editar {% endblock %}



{%block content %}

<link rel="stylesheet" href="{% static 'css/editar_perfil.css' %}">

<body>
    <br>
    <div class="edit">
    <div class="edit-header">
        <h1><span class="fas fa-users"></span> PERFIL</h1>
    </div>
    <form class="edit-form" action='' method="POST">
        {% csrf_token %}
        <h3><span class="fas fa-phone-square-alt"></span> Celular:</h3>
        {{form.celular}}<br>
        <h3><span class="fas fa-map-marker-alt"></span> Direccion:</h3>
        {{form.direccion}}
        <h3>Edad:</h3>
        {{form.edad}}<br>
        <h3><span class="fas fa-globe-americas"></span> Pais:</h3>
        {{form.pais}}
        <br>
        <br>
        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <script>
                    Swal.fire({
                      title: "{{error}}",
                      icon: "error" 
                    })      
                </script>
              {% endfor %}
          {% endfor %}
        {% endif %}
        <input id="boton" type="submit" value="Editar" class="btn btn-dark"/>
        <br>
    </form>
    </div>

</body>
        


{% endblock %}